package:
  name: kitsunetsuki-phys
  version: "0.2"

source:
  path: .

build:
  number: 0
  string: 1629798263

  missing_dso_whitelist:
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]

requirements:
  build:
    - bullet ==3.17
    - cmake
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - panda3d
    - python ==3.8
  run:
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - panda3d
    - python ==3.8

about:
  home: https://github.com/kitsune-ONE-team/KITSUNETSUKI-SDK
  license: BSD
