version: '3.4'

services:
  sdk:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ../jenkins:/root/jenkins:z
      - ../jenkins-jobs:/root/jenkins-jobs:z
      - ~/.config/jenkins_jobs/:/root/.config/jenkins_jobs:z
      - ~/Dev/Panda3D:/root/Dev/Panda3D:z
    environment:
      JENKINS_HOME: /root/jenkins
    command: >
      java -jar /opt/jenkins.war
      --httpPort=8080
      --logfile=/var/log/jenkins.log
      --debug=1
