#!/bin/sh

mkdir -p bld
cd bld
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_GLSL_EXTENSIONS=OFF \
    -DBUILD_LEGACY_LIVE_TEST=OFF \
    -DBUILD_NETWORK_DEVICE=OFF \
    -DBUILD_PYTHON_BINDINGS=ON \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_WITH_TM2=OFF \
    -DFORCE_RSUSB_BACKEND=true \
    -DUSE_EXTERNAL_USB=OFF \
    ..

make
make install

cd ..
