package:
  name: python-realsense
  version: "2.49"

source:
  - git_url: https://github.com/IntelRealSense/librealsense.git
    git_rev: v2.49.0

build:
  number: 0
  string: 1655223947

  missing_dso_whitelist:
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - $RPATH/libusb-1.0.so.0 # [unix]
    - /lib64/ld-linux-x86-64.so.2 # [unix]

requirements:
  build:
    - cmake
    - conda ==4.13.0
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - python ==3.10.0
  run:
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - python >=3.10.0,<3.11.0

about:
  home: https://www.intelrealsense.com
  license: Apache
