package:
  name: python-realsense
  version: "2.49"

source:
  - git_url: https://github.com/IntelRealSense/librealsense.git
    git_rev: v2.49.0

build:
  number: 0
  string: 1631255844

  missing_dso_whitelist:
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libm.so.6 # [unix]

requirements:
  build:
    - cmake
    - conda ==4.10.3
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - python ==3.9.6
  run:
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - python >=3.9.6,<3.10.0

about:
  home: https://www.intelrealsense.com
  license: Apache
