package:
  name: python-realsense
  version: "2.51"

source:
  - git_url: https://github.com/IntelRealSense/librealsense.git
    git_rev: v2.51.1

build:
  number: 0
  string: 1661929036

  missing_dso_whitelist:
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - $RPATH/libusb-1.0.so.0 # [unix]
    - /lib64/ld-linux-x86-64.so.2 # [unix]

requirements:
  build:
    - cmake==3.22.1
    - conda==23.3.1
    - python==3.10.0
  run:
    - python >=3.10.0,<3.11.0

about:
  home: https://www.intelrealsense.com
  license: Apache
