package:
  name: panda3d-kphys
  version: "0.5.4"

source:
  git_rev: 0.5.4
  git_url: https://github.com/kitsune-ONE-team/panda3d-kphys.git

build:
  number: 0
  string: 1688830779

  missing_dso_whitelist:
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]
    - lib/libgcc_s.so.1
    - lib/libstdc++.so.6

requirements:
  build:
    - bullet==3.17
    - cmake==3.22.1
    - conda==23.3.1
    - panda3d
    - python==3.10.0
  run:
    - panda3d
    - python >=3.10.0,<3.11.0

about:
  home: https://github.com/kitsune-ONE-team/panda3d-kphys
  license: MIT
