version: '3.4'

services:
  jenkins:
    image: jenkins/jenkins:2.492.3-jdk21
    ports:
      - '8080:8080'
    volumes:
      - ../jenkins-host:/var/jenkins_home:z
    networks:
      - sdk

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - '8022:22'
    networks:
      - sdk
    volumes:
      - .:/var/opt/kitsunetsuki-sdk:z
    command: bash -c "mkdir /run/sshd && /usr/sbin/sshd -D"

  sdk:
    build:
      context: .
      dockerfile: Dockerfile.sdk
    volumes:
      - .:/var/opt/kitsunetsuki-sdk:z
      - ~/Dev/Panda3D:/root/Dev/Panda3D:z
      - ~/var/mnt/games/steamapps/common/Blender:/root/Blender:z
      - ~/Public:/root/Public:z
    command: bash -c "mkdir /run/sshd && /usr/sbin/sshd -D"
    network_mode: "slirp4netns:allow_host_loopback=true"

networks:
  sdk:
    driver: bridge
