- job:
    name: dist-clean-lynx64
    display-name: dist-clean-lynx64
    project-type: freestyle
    description: Clean up "dist" for all jobs.
    node: linux
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    builders:
        - shell: |
            JENKINS_WS=${{JENKINS_HOME}}/workspace

            if [ -d ${{JENKINS_WS}}/bullet-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/bullet-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/ogg-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/ogg-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/vorbis-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/vorbis-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/sdl-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/sdl-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/python-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/python-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/panda3d-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/panda3d-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/panda3d-kphys-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/panda3d-kphys-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/panda3d-krender-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/panda3d-krender-lynx64/dist
            fi

            if [ -d ${{JENKINS_WS}}/sdk-lynx64 ]; then
                rm -Rf ${{JENKINS_WS}}/sdk-lynx64/dist
            fi

- job:
    name: dist-clean-winx64
    display-name: dist-clean-winx64
    project-type: freestyle
    description: Clean up "dist" for all jobs.
    node: windows
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    builders:
        - batch: |
            set JENKINS_WS=%HOME%\Jenkins\Jenkins\workspace

            if exist %JENKINS_WS%\bullet-winx64 (
                rd /S /Q %JENKINS_WS%\bullet-winx64\dist
            )

            if exist %JENKINS_WS%\sdl-winx64 (
                rd /S /Q %JENKINS_WS%\sdl-winx64\dist
            )

            if exist %JENKINS_WS%\python-winx64 (
                rd /S /Q %JENKINS_WS%\python-winx64\dist
            )

            if exist %JENKINS_WS%\panda3d-winx64 (
                rd /S /Q %JENKINS_WS%\panda3d-winx64\dist
            )

            if exist %JENKINS_WS%\panda3d-kphys-winx64 (
                rd /S /Q %JENKINS_WS%\panda3d-kphys-winx64\dist
            )

            if exist %JENKINS_WS%\panda3d-krender-winx64 (
                rd /S /Q %JENKINS_WS%\panda3d-krender-winx64\dist
            )

            if exist %JENKINS_WS%\sdk-winx64 (
                rd /S /Q %JENKINS_WS%\sdk-winx64\dist
            )

- job:
    name: pipeline-lynx64
    display-name: pipeline-lynx64
    project-type: pipeline
    description: KITSUNETSUKI SDK pipeline
    node: windows
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    dsl: |
      pipeline {{
          agent any
          stages {{
              stage('dist-clean') {{
                  steps {{ build job: 'dist-clean-lynx64' }}
              }}
              stage('bullet') {{
                  steps {{ build job: 'bullet-lynx64' }}
              }}
              stage('ogg') {{
                  steps {{ build job: 'ogg-lynx64' }}
              }}
              stage('vorbis') {{
                  steps {{ build job: 'vorbis-lynx64' }}
              }}
              stage('sdl') {{
                  steps {{ build job: 'sdl-lynx64' }}
              }}
              stage('python') {{
                  steps {{ build job: 'python-lynx64' }}
              }}
              stage('panda3d') {{
                  steps {{ build job: 'panda3d-lynx64' }}
              }}
              stage('panda3d-kphys') {{
                  steps {{ build job: 'panda3d-kphys-lynx64' }}
              }}
              stage('panda3d-krender') {{
                  steps {{ build job: 'panda3d-krender-lynx64' }}
              }}
              stage('sdk') {{
                  steps {{ build job: 'sdk-lynx64' }}
              }}
          }}
      }}

- job:
    name: pipeline-winx64
    display-name: pipeline-winx64
    project-type: pipeline
    description: KITSUNETSUKI SDK pipeline
    node: windows
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    dsl: |
      pipeline {{
          agent any
          stages {{
              stage('dist-clean') {{
                  steps {{ build job: 'dist-clean-winx64' }}
              }}
              stage('bullet') {{
                  steps {{ build job: 'bullet-winx64' }}
              }}
              stage('sdl') {{
                  steps {{ build job: 'sdl-winx64' }}
              }}
              stage('python') {{
                  steps {{ build job: 'python-winx64' }}
              }}
              stage('panda3d') {{
                  steps {{ build job: 'panda3d-winx64' }}
              }}
              stage('panda3d-kphys') {{
                  steps {{ build job: 'panda3d-kphys-winx64' }}
              }}
              stage('panda3d-krender') {{
                  steps {{ build job: 'panda3d-krender-winx64' }}
              }}
              stage('sdk') {{
                  steps {{ build job: 'sdk-winx64' }}
              }}
          }}
      }}
