package:
  name: kitsunetsuki-runtime
  version: "0.7"

source:
  path: .

build:
  number: 0
  string: 1646054371

  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libCg.so # [unix]
    - $RPATH/libCgGL.so # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libX11.so.6 # [unix]
    - $RPATH/libXrender.so.1 # [unix]
    - $RPATH/libasound.so.2 # [unix]
    - $RPATH/libbsd.so.0 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libopenal.so.1 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - $RPATH/librt.so.1 # [unix]
    - $RPATH/libsndio.so.7.0 # [unix]
    - $RPATH/libutil.so.1 # [unix]
    - $RPATH\api-ms-win-core-winrt-error-l1-1-0.dll # [win]
    - $RPATH\api-ms-win-core-winrt-l1-1-0.dll # [win]
    - $RPATH\api-ms-win-core-winrt-string-l1-1-0.dll # [win]
    - $RPATH\libffi-7.dll # [win]
    - $RPATH\pgort140.DLL # [win]
    - C:\Windows\System32\GLU32.dll # [win]
    - C:\Windows\System32\IPHLPAPI.DLL # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SETUPAPI.dll # [win]
    - C:\Windows\System32\SHLWAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]
    - C:\Windows\System32\VERSION.dll # [win]
    - C:\Windows\System32\WINMM.dll # [win]
    - C:\Windows\System32\WSOCK32.dll # [win]
    - Library\bin\MSVCP140.dll # [win]
    - Library\bin\VCRUNTIME140.dll # [win]

requirements:
  build:
    - conda ==4.10.3
    - idna
    - jsonschema ==3.2.0
    - kitsunetsuki-phys
    - panda3d
    - pyrsistent
    - pytest-runner
    - python ==3.9.6
    - six
  run:
    - freetype # [unix]
    - harfbuzz # [unix]
    - libffi
    - libgcc-ng # [unix]
    - libogg # [unix]
    - libpng
    - libstdcxx-ng # [unix]
    - libvorbis # [unix]
    - openssl >=1.1.1g
    - panda3d
    - python >=3.9.6,<3.10.0
    - xz # [unix]
    - zlib

about:
  home: https://kitsune.one/
  license: BSD
