package:
  name: kitsunetsuki-runtime
  version: "0.8"

source:
  path: .

build:
  number: 0
  string: 1688734465

  missing_dso_whitelist:
    - $RPATH/D3DCOMPILER_43.dll
    - $RPATH/D3DCOMPILER_43.dll
    - $RPATH/api-ms-win-core-path-l1-1-0.dll
    - $RPATH/api-ms-win-core-winrt-error-l1-1-0.dll
    - $RPATH/api-ms-win-core-winrt-l1-1-0.dll
    - $RPATH/api-ms-win-core-winrt-string-l1-1-0.dll
    - $RPATH/d3dx10_43.dll
    - $RPATH/d3dx11_43.dll
    - $RPATH/ld-linux-x86-64.so.2
    - $RPATH/libCg.so
    - $RPATH/libCgGL.so
    - $RPATH/libEGL.so.1
    - $RPATH/libGL.so.1
    - $RPATH/libGLESv1_CM.so.1
    - $RPATH/libGLESv2.so.2
    - $RPATH/libGLX.so.0
    - $RPATH/libOpenGL.so.0
    - $RPATH/libX11.so.6
    - $RPATH/libXrender.so.1
    - $RPATH/libasound.so.2
    - $RPATH/libbsd.so.0
    - $RPATH/libc.so.6
    - $RPATH/libdl.so.2
    - $RPATH/libffi-7.dll
    - $RPATH/libm.so.6
    - $RPATH/libopenal.so.1
    - $RPATH/libpthread.so.0
    - $RPATH/librt.so.1
    - $RPATH/libsndio.so.7
    - $RPATH/libsndio.so.7.0
    - $RPATH/libutil.so.1
    - $RPATH/pgort140.DLL
    - /lib64/ld-linux-x86-64.so.2
    - C:\Windows\System32\GLU32.dll
    - C:\Windows\System32\IPHLPAPI.DLL
    - C:\Windows\System32\MSVCP140.dll
    - C:\Windows\System32\OPENGL32.dll
    - C:\Windows\System32\SETUPAPI.dll
    - C:\Windows\System32\SHLWAPI.dll
    - C:\Windows\System32\VCRUNTIME140.dll
    - C:\Windows\System32\VCRUNTIME140_1.dll
    - C:\Windows\System32\VERSION.dll
    - C:\Windows\System32\WINMM.dll
    - C:\Windows\System32\WSOCK32.dll
    - Library/bin/MSVCP140.dll
    - Library/bin/VCRUNTIME140.dll

requirements:
  build:
    - conda==23.3.1
    - idna
    - jsonschema==3.2.0
    - panda3d-kphys==0.5.3
    - panda3d-krender==0.0.14
    - panda3d==1.10.13
    - pyparsing
    - pyrsistent
    - pytest-runner
    - python==3.10.0
    - six
  run:
    - bzip2
    - jpeg # [unix]
    - libffi
    - libgcc-ng # [unix]
    - libpng
    - libstdcxx-ng # [unix]
    - libtiff # [unix]
    - libuuid # [unix]
    - openssl
    - panda3d
    - python >=3.10.0,<3.11.0
    - pywin32 # [win]
    - xz
    - zlib

about:
  home: https://kitsune.one/
  license: BSD
