package:
  name: kcc
  version: "0.1"

source:
  path: .

build:
  number: 0
  string: 1586123943

requirements:
  build:
    - cmake
    - bullet ==2.83
    - panda3d-kitsunetsuki >=1.10.6
  run:
    - panda3d-kitsunetsuki >=1.10.6

about:
  home: https://github.com/Yonnji/KITSUNETSUKI-SDK
  license: BSD
