#!/bin/sh
THIRDPARTY=lib/linux_centos7_x86_64
PYTHON_VERSION=3.10

# remove included python
rm -Rf ${THIRDPARTY}/python

mkdir -p blender/bld

cd blender

cd bld
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DLIBSNDFILE_ROOT_DIR=THIRDPARTY/sndfile \
    -DPYTHON_INCLUDE_DIR=${CONDA_PREFIX}/include/python${PYTHON_VERSION} \
    -DPYTHON_LIBRARY=${CONDA_PREFIX}/lib/libpython${PYTHON_VERSION}.so \
    -DPYTHON_VERSION=${PYTHON_VERSION} \
    -DWITH_AUDASPACE=ON \
    -DWITH_CODEC_AVI=ON \
    -DWITH_CODEC_FFMPEG=ON \
    -DWITH_CODEC_SNDFILE=ON \
    -DWITH_CYCLES=ON \
    -DWITH_CYCLES_EMBREE=ON \
    -DWITH_DRACO=OFF \
    -DWITH_FREESTYLE=OFF \
    -DWITH_GLEW_ES=OFF \
    -DWITH_GLEW_MX=OFF \
    -DWITH_GLU=OFF \
    -DWITH_HEADLESS=ON \
    -DWITH_INSTALL_PORTABLE=OFF \
    -DWITH_JACK=OFF \
    -DWITH_LLVM=OFF \
    -DWITH_MEM_JEMALLOC=OFF \
    -DWITH_MOD_OCEANSIM=OFF \
    -DWITH_OPENAL=OFF \
    -DWITH_OPENCOLLADA=OFF \
    -DWITH_OPENCOLORIO=OFF \
    -DWITH_OPENIMAGEDENOISE=ON \
    -DWITH_OPENIMAGEIO=ON \
    -DWITH_OPENMP=OFF \
    -DWITH_OPENSUBDIV=ON \
    -DWITH_PYTHON_INSTALL=OFF \
    -DWITH_PYTHON_INSTALL_NUMPY=OFF \
    -DWITH_PYTHON_MODULE=ON \
    -DWITH_SDL=OFF \
    -DWITH_STATIC_LIBS=OFF \
    -DWITH_TBB=OFF \
    -DWITH_X11_XINPUT=OFF \
    ..

make
make install

cd ..
