package:
  name: python-blender
  version: "2.90"

source:
  - git_url: git://git.blender.org/blender-addons.git
    git_rev: v2.90.0
    folder: blender_extras/release/scripts/addons

  - git_url: git://git.blender.org/blender-addons-contrib.git
    git_rev: v2.90.0
    folder: blender_extras/release/scripts/addons_contrib

  - git_url: git://git.blender.org/blender-translations.git
    git_rev: v2.90.0
    folder: blender_extras/release/datafiles/locale

  - git_url: git://git.blender.org/blender-dev-tools.git
    git_rev: v2.90.0
    folder: blender_extras/source/tools

  - git_url: git://git.blender.org/blender.git
    git_rev: v2.90.0
    folder: blender
    patches:
      - platform.patch # [win]

  # - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14 # [win32]
  #   folder: lib/windows_vc14 # [win32]

  # - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 # [win64]
  #   folder: lib/win64_vc14 # [win64]

build:
  number: 0
  string: 1599603091

  missing_dso_whitelist:
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - C:\Windows\System32\AVIFIL32.dll # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SHFOLDER.dll # [win]
    - C:\Windows\System32\SHLWAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]

requirements:
  build:
    - blender-thirdparty # [unix]
    - bullet
    - cmake
    - fontconfig # [unix]
    - freetype # [unix]
    - git
    - jpeg
    - libgcc # [unix]
    - libpng # [unix]
    - libtiff # [unix]
    - llvmdev # [unix]
    - m2-patch # [win]
    - openjpeg
    - python >=3.8
    - requests # [unix]
    - zlib
  run:
    - freetype # [unix]
    - jpeg # [unix]
    - libgcc # [unix]
    - libpng # [unix]
    - libtiff # [unix]
    - python >=3.8
    - zlib # [unix]

about:
  home: https://www.blender.org/
  license: GPL
