package:
  name: python-blender
  version: "3.6.0"

source:
  - git_url: https://projects.blender.org/blender/blender.git
    git_rev: v3.6.0
    folder: blender

  - git_url: https://projects.blender.org/blender/blender-addons.git
    git_rev: v3.6.0
    folder: scripts/addons

  - git_url: https://projects.blender.org/blender/blender-addons-contrib.git
    git_rev: v3.6.0
    folder: scripts/addons_contrib

  - svn_url: https://svn.blender.org/svnroot/bf-blender/tags/blender-3.6-release/lib/win64_vc15 # [win64]
    folder: lib/win64_vc15 # [win64]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_x86_64_glibc_228 # [unix]
    folder: lib/linux_x86_64_glibc_228 # [unix]

build:
  number: 0
  string: 1688731267

  missing_dso_whitelist:
    - $RPATH/api-ms-win-core-path-l1-1-0.dll # [win]
    - $RPATH/avcodec-59.dll # [win]
    - $RPATH/avdevice-59.dll # [win]
    - $RPATH/avformat-59.dll # [win]
    - $RPATH/avutil-57.dll # [win]
    - $RPATH/epoxy-0.dll # [win]
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libgmp-10.dll # [win]
    - $RPATH/libgmpxx.dll # [win]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - $RPATH/libsndfile-1.dll # [win]
    - $RPATH/swresample-4.dll # [win]
    - $RPATH/swscale-6.dll # [win]
    - $RPATH/tbbmalloc.dll # [win]
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - C:\Windows\System32\AVIFIL32.dll # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SHFOLDER.dll # [win]
    - C:\Windows\System32\SHLWAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]

requirements:
  build:
    - bullet
    - cmake
    - conda ==4.13.0
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - m2-patch # [win]
    - numpy >=1.22.3
    - python ==3.10.0
  run:
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - numpy >=1.22.3
    - python >=3.10.0,<3.11.0
    - zlib

about:
  home: https://www.blender.org/
  license: GPL
