package:
  name: python-blender
  version: "3.6.0"

source:
  - git_url: https://projects.blender.org/blender/blender.git
    git_rev: v3.6.0
    folder: blender

  - git_url: https://projects.blender.org/blender/blender-addons.git
    git_rev: v3.6.0
    folder: blender/scripts/addons

  - git_url: https://projects.blender.org/blender/blender-addons-contrib.git
    git_rev: v3.6.0
    folder: blender/scripts/addons_contrib

  - svn_url: https://svn.blender.org/svnroot/bf-blender/tags/blender-3.6-release/lib/assets
    folder: lib/assets

  - svn_url: https://svn.blender.org/svnroot/bf-blender/tags/blender-3.6-release/lib/win64_vc15 # [win64]
    folder: lib/win64_vc15 # [win64]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_x86_64_glibc_228 # [unix]
    folder: lib/linux_x86_64_glibc_228 # [unix]

build:
  number: 0
  string: 1688731267

  missing_dso_whitelist:
    - $RPATH/api-ms-win-core-path-l1-1-0.dll
    - $RPATH/avcodec-59.dll
    - $RPATH/avdevice-59.dll
    - $RPATH/avformat-59.dll
    - $RPATH/avutil-57.dll
    - $RPATH/epoxy-0.dll
    - $RPATH/ld-linux-x86-64.so.2
    - $RPATH/libGL.so.1
    - $RPATH/libGLU.so.1
    - $RPATH/libGLX.so.0
    - $RPATH/libICE.so.6
    - $RPATH/libOpenGL.so.0
    - $RPATH/libSM.so.6
    - $RPATH/libX11.so.6
    - $RPATH/libXext.so.6
    - $RPATH/libXt.so.6
    - $RPATH/libc.so.6
    - $RPATH/libdl.so.2
    - $RPATH/libgmp-10.dll
    - $RPATH/libgmpxx.dll
    - $RPATH/libm.so.6
    - $RPATH/libmvec.so.1
    - $RPATH/libpthread.so.0
    - $RPATH/librt.so.1
    - $RPATH/libsndfile-1.dll
    - $RPATH/libutil.so.1
    - $RPATH/swresample-4.dll
    - $RPATH/swscale-6.dll
    - $RPATH/tbbmalloc.dll
    - /lib64/ld-linux-x86-64.so.2
    - C:\Windows\System32\AVIFIL32.dll
    - C:\Windows\System32\MSVCP140.dll
    - C:\Windows\System32\OPENGL32.dll
    - C:\Windows\System32\SHFOLDER.dll
    - C:\Windows\System32\SHLWAPI.dll
    - C:\Windows\System32\VCRUNTIME140.dll
    - C:\Windows\System32\VCRUNTIME140_1.dll

requirements:
  build:
    - bullet
    - cmake==3.22.1
    - conda==23.3.1
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - m2-patch # [win]
    - numpy >=1.22.3
    - python==3.10.0
  run:
    - libgcc-ng # [unix]
    - libstdcxx-ng # [unix]
    - numpy >=1.22.3
    - python >=3.10.0,<3.11.0
    - zlib

about:
  home: https://www.blender.org/
  license: GPL
