package:
  name: python-blender
  version: "2.93.4"

source:
  - git_url: https://git.blender.org/blender.git
    git_rev: v2.93.4
    folder: blender

  - git_url: https://git.blender.org/blender-addons.git
    git_rev: v2.93.4
    folder: blender_extras/release/scripts/addons

  - git_url: https://git.blender.org/blender-addons-contrib.git
    git_rev: v2.93.4
    folder: blender_extras/release/scripts/addons_contrib

  - git_url: https://git.blender.org/blender-translations.git
    git_rev: v2.93.4
    folder: blender_extras/release/datafiles/locale

  - git_url: https://git.blender.org/blender-dev-tools.git
    git_rev: v2.93.4
    folder: blender_extras/source/tools

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15 # [win64]
    folder: lib/win64_vc15 # [win64]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64 # [unix]
    folder: lib/linux_centos7_x86_64 # [unix]

build:
  number: 0
  string: 1614533233

  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - C:\Windows\System32\AVIFIL32.dll # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SHFOLDER.dll # [win]
    - C:\Windows\System32\SHLWAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]

requirements:
  build:
    - bullet
    - cmake
    - conda ==4.10.3
    - fontconfig # [unix]
    - freetype # [unix]
    - git
    - jpeg
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libtiff # [unix]
    - llvmdev # [unix]
    - m2-patch # [win]
    - numpy
    - openjpeg
    - python ==3.9.6
    - requests # [unix]
    - zlib
  run:
    - freetype # [unix]
    - jpeg # [unix]
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libtiff # [unix]
    - numpy
    - python >=3.9.6,<3.10.0
    - zlib # [unix]

about:
  home: https://www.blender.org/
  license: GPL
