- job-template:
    name: clean-{path}-lynx64
    display-name: clean-{path}-lynx64
    project-type: freestyle
    description: Clean up "{path}" for all jobs.
    node: linux
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    builders:
        - shell: |
            rm -Rf /app/{path}/*

- job-template:
    name: clean-{path}-winx64
    display-name: clean-{path}-winx64
    project-type: freestyle
    description: Clean up "{path}" for all jobs.
    node: windows
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    builders:
        - batch: |
            rd /S /Q C:\{path}
            rd /S /Q Z:\{path}

- job-template:
    name: 'pipeline-{arch}'
    display-name: 'pipeline-{arch}'
    project-type: pipeline
    description: KITSUNETSUKI SDK pipeline
    node: '{node}'
    build-discarder:
        daysToKeep: -1
        numToKeep: 2
        artifactDaysToKeep: -1
        artifactNumToKeep: -1
    dsl: |
      pipeline {{
          agent any
          stages {{
              stage('clean-opt') {{
                  steps {{ build job: 'clean-opt-{arch}' }}
              }}
              stage('freetype') {{
                  steps {{ build job: 'freetype-{arch}' }}
              }}
              stage('harfbuzz') {{
                  steps {{ build job: 'harfbuzz-{arch}' }}
              }}
              stage('ogg') {{
                  steps {{ build job: 'ogg-{arch}' }}
              }}
              stage('panda3d-reqs') {{
                  parallel {{
                      stage('bullet') {{
                          steps {{ build job: 'bullet-{arch}' }}
                      }}
                      stage('freetypehb') {{
                          steps {{ build job: 'freetypehb-{arch}' }}
                      }}
                      stage('python') {{
                          steps {{ build job: 'python-{arch}' }}
                      }}
                      stage('sdl') {{
                          steps {{ build job: 'sdl-{arch}' }}
                      }}
                      stage('vorbis') {{
                          steps {{ build job: 'vorbis-{arch}' }}
                      }}
                  }}
              }}
              stage('interrogate') {{
                  steps {{ build job: 'interrogate-{arch}' }}
              }}
              stage('panda3d') {{
                  steps {{ build job: 'panda3d-{arch}' }}
              }}
              stage('panda3d-plugins') {{
                  parallel {{
                      stage('panda3d-kphys') {{
                          steps {{ build job: 'panda3d-kphys-{arch}' }}
                      }}
                      stage('panda3d-krender') {{
                          steps {{ build job: 'panda3d-krender-{arch}' }}
                      }}
                  }}
              }}
              stage('sdk') {{
                  steps {{ build job: 'sdk-{arch}' }}
              }}
          }}
      }}

- project:
    name: clean-build
    jobs:
        - 'clean-{path}-lynx64':
            path: build
        - 'clean-{path}-winx64':
            path: build

- project:
    name: clean-opt
    jobs:
        - 'clean-{path}-lynx64':
            path: opt
        - 'clean-{path}-winx64':
            path: opt

- project:
    name: pipeline
    jobs:
        - 'pipeline-{arch}':
            arch: lynx64
            node: linux
        - 'pipeline-{arch}':
            arch: winx64
            node: windows
