package:
  name: panda3d
  version: "1.10.11"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: ce7c1ec16c5a0b0ceb7c9bebb30e85e76e34592f
    folder: .
    patches:
      - bullet3.patch
      - bullet_char.patch
      - icon.patch # [unix]
      - libs.patch
      - nopy.patch # [win]
      - prefix.patch # [win]
      - rgba.patch # [unix]
      - rp_light.patch

  - url: https://www.panda3d.org/download/panda3d-1.10.11/panda3d-1.10.11-tools-win64.zip # [win64]
    md5: a2eca781871274f5a05bc4bc74b419ad # [win64]

build:
  number: 0
  string: 1643296472

  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libCg.so # [unix]
    - $RPATH/libCgGL.so # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libX11.so.6 # [unix]
    - $RPATH/libXrender.so.1 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libopenal.so.1 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - C:\Windows\System32\GLU32.dll # [win]
    - C:\Windows\System32\IPHLPAPI.DLL # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SETUPAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]
    - C:\Windows\System32\WINMM.dll # [win]
    - C:\Windows\System32\WSOCK32.dll # [win]
    - Library\bin\MSVCP140.dll # [win]
    - Library\bin\VCRUNTIME140.dll # [win]

requirements:
  build:
    - bullet ==3.17
    - cmake
    - conda ==4.10.3
    - fontconfig # [unix]
    - freetype # [unix]
    - harfbuzz # [unix]
    - libgcc-ng # [unix]
    - libogg # [unix]
    - libpng
    - libstdcxx-ng # [unix]
    - libvorbis # [unix]
    - m2-gcc-libs # [win]
    - m2-p7zip # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - openssl >=1.1.1g
    - patchelf # [unix]
    - pillow # [unix]
    - python ==3.9.6
    - zlib
  run:
    - freetype # [unix]
    - harfbuzz # [unix]
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libvorbis # [unix]
    - python >=3.9.6,<3.10.0
    - vs2015_runtime # [win]
    - zlib # [unix]

about:
  home: http://www.panda3d.org/
  license: BSD
