package:
  name: panda3d
  version: "1.10.13"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: v1.10.13
    folder: .
    patches:
      - 01_libs.patch
      - 02_bullet_char.patch
      - 03_icon.patch # [unix]
      - 05_py_noinst.patch # [win]
      - 06_py_prefix.patch # [win]
      - 07_rgba.patch # [unix]
      # - 08_kbd.patch # [unix]
      - 09_rp_light.patch
      - 10_libp3rplight.patch

  - url: https://www.panda3d.org/download/panda3d-1.10.13/panda3d-1.10.13-tools-win64.zip # [win64]
    md5: d51607cff36314ab1ac5911123820277 # [win64]

  - svn_url: https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_x86_64_glibc_228 # [unix]
    folder: lib/linux_x86_64_glibc_228 # [unix]

build:
  number: 0
  string: 1688830779

  missing_dso_whitelist:
    - $RPATH/D3DCOMPILER_43.dll
    - $RPATH/d3dx10_43.dll
    - $RPATH/d3dx11_43.dll
    - $RPATH/ld-linux-x86-64.so.2
    - $RPATH/libCg.so
    - $RPATH/libCgGL.so
    - $RPATH/libEGL.so.1
    - $RPATH/libGL.so.1
    - $RPATH/libGLESv1_CM.so.1
    - $RPATH/libGLESv2.so.2
    - $RPATH/libGLX.so.0
    - $RPATH/libOpenGL.so.0
    - $RPATH/libX11.so.6
    - $RPATH/libXrender.so.1
    - $RPATH/libc.so.6
    - $RPATH/libdl.so.2
    - $RPATH/libm.so.6
    - $RPATH/libopenal.so.1
    - $RPATH/libpthread.so.0
    - /lib64/ld-linux-x86-64.so.2
    - C:\Windows\System32\GLU32.dll
    - C:\Windows\System32\IPHLPAPI.DLL
    - C:\Windows\System32\MSVCP140.dll
    - C:\Windows\System32\OPENGL32.dll
    - C:\Windows\System32\SETUPAPI.dll
    - C:\Windows\System32\VCRUNTIME140.dll
    - C:\Windows\System32\VCRUNTIME140_1.dll
    - C:\Windows\System32\WINMM.dll
    - C:\Windows\System32\WSOCK32.dll
    - Library\bin\MSVCP140.dll
    - Library\bin\VCRUNTIME140.dll
    - lib/libgcc_s.so.1
    - lib/libstdc++.so.6

requirements:
  build:
    - bison # [unix]
    - bullet==3.17
    - cmake==3.22.1
    - conda==23.3.1
    - fontconfig # [unix]
    - freetype # [unix]
    - harfbuzz # [unix]
    - jpeg # [unix]
    - libogg # [unix]
    - libpng
    - libtiff # [unix]
    - libvorbis # [unix]
    - m2-gcc-libs # [win]
    - m2-p7zip # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - openssl
    - patchelf # [unix]
    - pillow # [unix]
    - python==3.10.0
    - zlib
  run:
    - jpeg # [unix]
    - libpng # [unix]
    - libtiff # [unix]
    - python >=3.10.0,<3.11.0
    - vs2015_runtime # [win]
    - zlib # [unix]

about:
  home: http://www.panda3d.org/
  license: BSD
