package:
  name: panda3d
  version: "1.10.8"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: 51a3a2b4a1c10f3161c9dbfb2a975bd396913049
    folder: .
    patches:
      - bullet.patch
      - bullet3.patch
      - fabrik108.patch
      - icon108.patch # [unix]
      - libs.patch
      - nopy.patch # [win]
      - prefix108.patch # [win]
      - rp_light.patch
      - udp.patch
      - vs2022.patch # [win]
      - rgba.patch # [unix]

  # - url: https://www.panda3d.org/download/panda3d-1.10.8/panda3d-1.10.8-tools-win32.zip # [win32]
  #   md5: 5841b1527c20a2a697784710e60fcfdf # [win32]

  - url: https://www.panda3d.org/download/panda3d-1.10.7/panda3d-1.10.7-tools-win32.zip # [win32]
    md5: 037e5109878ff943e0342c61ee39fdca # [win32]

  # - url: https://www.panda3d.org/download/panda3d-1.10.8/panda3d-1.10.8-tools-win64.zip # [win64]
  #   md5: d17e997dfb2a84e4b935a930650df053 # [win64]

  - url: https://www.panda3d.org/download/panda3d-1.10.7/panda3d-1.10.7-tools-win64.zip # [win64]
    md5: ed1438c59471abd1ee11e3414c97e0fe # [win64]

build:
  number: 0
  string: 1634119168

  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/ld-linux-x86-64.so.2 # [unix]
    - $RPATH/libCg.so # [unix]
    - $RPATH/libCgGL.so # [unix]
    - $RPATH/libGL.so.1 # [unix]
    - $RPATH/libX11.so.6 # [unix]
    - $RPATH/libc.so.6 # [unix]
    - $RPATH/libdl.so.2 # [unix]
    - $RPATH/libm.so.6 # [unix]
    - $RPATH/libopenal.so.1 # [unix]
    - $RPATH/libpthread.so.0 # [unix]
    - C:\Windows\System32\GLU32.dll # [win]
    - C:\Windows\System32\IPHLPAPI.DLL # [win]
    - C:\Windows\System32\MSVCP140.dll # [win]
    - C:\Windows\System32\OPENGL32.dll # [win]
    - C:\Windows\System32\SETUPAPI.dll # [win]
    - C:\Windows\System32\VCRUNTIME140.dll # [win]
    - C:\Windows\System32\VCRUNTIME140_1.dll # [win]
    - C:\Windows\System32\WINMM.dll # [win]
    - C:\Windows\System32\WSOCK32.dll # [win]
    - Library\bin\MSVCP140.dll # [win]
    - Library\bin\VCRUNTIME140.dll # [win]

requirements:
  build:
    - bullet ==3.17
    - cmake
    - conda ==4.10.3
    - fontconfig # [unix]
    - freetype # [unix]
    - libgcc-ng # [unix]
    - libogg # [unix]
    - libpng
    - libstdcxx-ng # [unix]
    - libvorbis # [unix]
    - m2-gcc-libs # [win]
    - m2-p7zip # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - openssl >=1.1.1g
    - patchelf # [unix]
    - pillow # [unix]
    - python ==3.9.6
    - zlib
  run:
    - freetype # [unix]
    - libgcc-ng # [unix]
    - libpng # [unix]
    - libstdcxx-ng # [unix]
    - libvorbis # [unix]
    - python >=3.9.6,<3.10.0
    - vs2015_runtime # [win]
    - zlib # [unix]

about:
  home: http://www.panda3d.org/
  license: BSD
