package:
  name: panda3d-kitsunetsuki
  version: "1.10.6"

source:
  - git_url: https://github.com/panda3d/panda3d.git
    git_rev: v1.10.6
    folder: .
    patches:
      - prefix-110.patch # [win]
      - nopy.patch # [win]
      - icon.patch # [unix]
      - bullet.patch
      - openssl.patch
      - egg1.patch
      - egg2.patch
      - egg3.patch
      - rp_light.patch

  - url: https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6-tools-win32.zip # [win32]
    md5: 04d6b4406b3ab9c2452c76eb4f36be7a # [win32]

  - url: https://www.panda3d.org/download/panda3d-1.10.6/panda3d-1.10.6-tools-win64.zip # [win64]
    md5: 3bcd5c75bd875333aed01b98a8ec2f8f # [win64]

build:
  number: 0
  string: 1586715300

requirements:
  build:
    - python <3.8
    - openssl >=1.1.1f
    - cmake
    - bullet ==2.83
    - pillow # [unix]
    - m2-gcc-libs # [win]
    - m2-patch # [win]
    - msinttypes # [win]
    - 7za # [win]
    - fontconfig # [unix]
    - freetype # [unix]
    - libpng
  run:
    - python <3.8
    - fontconfig # [unix]
    - freetype # [unix]
    - libpng

about:
  home: http://www.panda3d.org/
  license: BSD
