#!/bin/sh

cmake \
    -DBUILD_BULLET2_DEMOS=OFF \
    -DBUILD_BULLET3=OFF \
    -DBUILD_CPU_DEMOS=OFF \
    -DBUILD_DEMOS=OFF \
    -DBUILD_EXTRAS=OFF \
    -DBUILD_MULTITHREADING=OFF \
    -DBUILD_OPENGL3_DEMOS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS=-fPIC \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DINSTALL_LIBS=ON

make
make install
