package:
  name: bullet
  version: "3.17"

source:
  git_rev: 3.17
  git_url: https://github.com/bulletphysics/bullet3.git

build:
  number: 0
  string: 1630952201

requirements:
  build:
    - cmake
    - conda ==4.10.3

c_compiler:
  - gcc # [linux]
  - vs2019 # [win]

cxx_compiler:
  - gxx # [linux]
  - vs2019 # [win]

about:
  home: http://bulletphysics.org
  license: Zlib
