package:
  name: bullet
  version: "3.17"

source:
  git_rev: 3.17
  git_url: https://github.com/bulletphysics/bullet3.git

build:
  number: 0
  string: 1667744461

requirements:
  build:
    - cmake==3.22.1
    - conda==4.13.0

about:
  home: http://bulletphysics.org
  license: Zlib
